### ISSUE TITLE
Add New Service Content Sections 

### ISSUE THREAD

**Issue by bamboochow** [pcl-labs/vodworks-storyblok#37]
# Product Engineering
Add a section for "happy highlights" with the content below, plus a button that links to the project's work lightbox (url coming up). 
These sections should have the same margins/spacings as the image/text section above, just with the images and text halves switched. 

![image](https://user-images.githubusercontent.com/14948326/129066341-c6e6c6f8-0e0b-4a57-874f-d45fa8030c09.png)

## Content
Title: Happy Highlights: Music for Mental Health
Text: In an effort to combat the global mental health issues, Vodworks created Happy Highlights, a mood tracking app that helps users track, understand, and maintain their own mental wellbeing  Happy Highlights provides users analytics to better understand their own mental patterns, while providing options to improve their mood based on their needs. Features include: • Intuitive mood tracking system & diary  • Personalized mood-boosting music suggestions based on user library • Dashboard showing mood and acitivity over time for better understanding
Link: https://laughing-williams-80f81d.netlify.app/work/happy-highlights

# Media Solutions 

Add a section for "Vidscape" with the content below, plus a button that links to the project's work lightbox (url coming up). 
These sections should have the same margins/spacings as the image/text section above, just with the images and text halves switched. 

![image](https://user-images.githubusercontent.com/14948326/129067792-f7808d98-177f-4481-9872-3be6c136c146.png)

## Content 
Title: Vidscape: An Online TV Experience 
Text: VIDSCAPE is a full-featured content management, monetization and multiscreen delivery technology designed specifically to empower media and advertising industry through various features.

Having a rich background in media services, Vodworks has designed VidScape specifically for the online television and advertisement industry to help them deliver unmatched user experiences. Vidscape revolutionizes the media industry with features such as: 
 • highly-customizable fully featured OTT video service management 
 • multiscreen, user-focused interface
• a complete multi-algorithm content discovery engine. 
• a powerful, customizable data insights module
Link: https://laughing-williams-80f81d.netlify.app/work/vidscape

**Comment by giteshk11** [comment]
@bamboochow are these sections going to be just on some pages or all?
